### ISSUE TITLE
Hola, no me funcionó. No supe donde ejecutar npm install

### ISSUE THREAD

**Issue by josepintado24** [Aquive/Magetail#1]

**Comment by Aquive** [comment]
Run it from the theme root, for example: `app\design\frontend\Aqm\Magetail`

**Comment by psahni** [comment]
@Aquive there is no package.json in Magetail
Do you want us to init the project and install tailwind

**Comment by Aquive** [comment]
@psahni yeah I think so, I don't remember how it supposed to be. If you cannot get it working, I can try it on a test installation. Let me know.
